apiVersion: v1
kind: Pod
metadata:
  name: pod
  labels:
    function: webserver
spec:
  containers:
  - name: httpd
    image: ghcr.io/larry461/cis-92:milestone-5.2
    ports:
    - containerPort: 80
    env:
    - name: DB_NAME 
      value: "mysite"
    - name: DB_USER 
      value: postgres
    - name: DB_PASSWORD 
      value: "django"
    - name: DB_HOST 
      value: deployment/postgres-service.yaml      
    resources:
      requests:
        memory: "512Mi"
        cpu: "250m"
      limits:
        memory: "512Mi"
        cpu: "500m"   
    livenessProbe:
      httpGet:
        path: /polls/
        port: 8000 